<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?=$this->__('Mailrelay sync users')?></h3></td>
            <td class="a-right">
                <button onclick="index_form.submit()" class="scalable save" type="button"><span>Send</span></button>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <form id="index_form" name="index_form" method="post" action="<?=$this->getUrl('*/*/startsync')?>">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
        <h4 class="icon-head head-index-form fieldset-legend"><?=$this->__('User sync. Step 1 of 3 (validate)')?></h4>
        <fieldset id="my-fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><?=$this->__('Host')?></td>
                    <td class="input-ele"><input class="input-text required-entry" readonly="true" name="indexform[host]" value="<?php echo $this->sync_host; ?>" /></td>
                </tr>

                <tr>
                    <td class="label"><?=$this->__('User')?></td>
                    <td class="input-ele"><input class="input-text required-entry" readonly="true" name="indexform[user]" value="<?php echo $this->sync_user; ?>" /></td>
                </tr>

                <tr>
                    <td class="label"><?=$this->__('Password')?></td>
                    <td class="input-ele"><input class="input-text required-entry" readonly="true" name="indexform[password]" value="<?php echo $this->sync_pass; ?>" type="password" /></td>
                </tr>

            </table>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var editForm = new varienForm('index_form');
</script>
